name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.21.0 # TODO update
    permissions: {} # TODO update
    with:
      release_prefix: NISAR Docs
      fast_forward: false # TODO: implement this option, document lack of need for PAK with this option
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
